### ISSUE TITLE
loop exception

### ISSUE THREAD

**Issue by gsiehien** [jbreeden/mruby-erb#1]
HI!

There seems to be problem with rendering templates that have loops and are executed with the object.

``` ruby
template_obj_loop = <<FOO
  <p>hello <%= @x %>!</p>
  <% 10.times do |x|%>
    <%= x %>
  <% end %>
FOO

template_obj = <<FOO
  <p>hello! <%= @x %>!</p>
FOO

template_loop = <<FOO
  <% 10.times do |x|%>
   <%= x %>
  <% end %>
FOO

class MyClass
  def initialize(x)
    @x = x
  end
end

obj = MyClass.new "john"
puts ERB.new(template_obj).result(obj) #OK
puts ERB.new(template_loop).result #OK
puts ERB.new(template_obj_loop).result(obj) #FAILS 
# undefined method 'concat' for #<MyClass:0xa45c30 @x="john"> (NoMethodError)
```

**Comment by jbreeden** [comment]
Strange... the compiled template looks OK

```
> puts erb.instance_variable_get(:@src)
_erbout = ''; _erbout.concat "  <p>hello "; _erbout.concat(( @x ).to_s); _erbout.concat "!</p>\n  "
;  10.times do |x|; _erbout.concat "\n    "
; _erbout.concat(( x ).to_s); _erbout.concat "\n  "
;  end ; _erbout.concat "\n"
; _erbout
 => nil
```

And instance evaling the src on obj doesn't raise (which is what #result does)

```
> obj.instance_eval(erb.instance_variable_get(:@src), '(erb)', 0)
 => "  <p>hello john!</p>\n  \n"
```

But as soon as you call it from inside a method, it fails

```
> def test(obj, erb)
*  obj.instance_eval(erb.instance_variable_get(:@src), '(erb)', 0)
* end
 => :test
> test(obj, erb)
(erb):2: undefined method 'concat' for #<MyClass:0x7fa6048373c0 @x="john"> (NoMethodError)
```

There may be an issue with MRuby's instance_eval. I'll have to look into this more tomorrow. Long day of travel, so I'm spent for the night.

Thanks for reporting. I'll get back to you.

**Comment by jbreeden** [comment]
Opened https://github.com/mruby/mruby/issues/3072 with the MRuby guys. Sorry to say this is a bit beyond my expertise to solve for now. Until it's fixed, this port will be of limited use unless I can find some sort of workaround.

**Comment by jbreeden** [comment]
You could try using `ERB#def_method` if it's acceptable for you to define a method somewhere to render the template. It seems to work for your templates:

```
template_obj_loop = <<FOO
  <p>hello <%= @x %>!</p>
  <% 10.times do |x|%>
    <%= x %>
  <% end %>
FOO

template_obj = <<FOO
  <p>hello! <%= @x %>!</p>
FOO

template_loop = <<FOO
  <% 10.times do |x|%>
   <%= x %>
  <% end %>
FOO

class MyClass
  def initialize(x)
    @x = x
  end
end

obj = MyClass.new "john"
ERB.new(template_obj).def_method(MyClass, :temp1)
puts "template_obj:"
puts obj.temp1 #OK
ERB.new(template_loop).def_method(MyClass, :temp2)
puts "template_loop:"
puts obj.temp2 #OK
puts "template_obj_loop:"
ERB.new(template_obj_loop).def_method(MyClass, :temp3)
puts obj.temp3
```

```
[jared:~/projects/mruby-erb] mruby issue2.rb 
template_obj:
  <p>hello! john!</p>
template_loop:

   0

   1

   2

   3

   4

   5

   6

   7

   8

   9

template_obj_loop:
  <p>hello john!</p>

    0

    1

    2

    3

    4

    5

    6

    7

    8

    9

```

**Comment by gsiehien** [comment]
Thanks! The workaround will do for now.

**Comment by jbreeden** [comment]
No problem. Also, the def_method, def_module, & def_class methods should take parameters now (just pushed)... which can be used sort of like a binding. Should allow you to define a separate `Renderer` class or something, instead of making methods on the object to render. More importantly, it should _not_ have the same instance_eval problems as the regular `result` function. Let me know if you have any other problems.

```
tmp = "<%= a %> <%= b %>"
erb = ERB.new(tmp)
Renderer = erb.def_class(Object, 'render(a, b)')
renderer = Renderer.new
renderer.render(1, 2)
 => "1 2"
```

**Comment by jbreeden** [comment]
Fixed the issue.

Just using eval to compile the template code into a proc, then instance eval the proc on the target - which MRuby handles much better than strings. I ran your templates and they work for me.

Commit: 2333b90cd0e64fac7c9fd636d5348d3135c7825c
